http:
  listener:
    port: "9081"
    host: "localhost"
  requester:
    host: "localhost"
    port: "8081"
    routesPath: "travelOnTrip/routes"
    schedulesPath: "travelOnTrip/schedules"
db:
  oracle:
    host: "localhost"
    port: "1521"
    user: "admin"
    password: "admin"
    instance: ""
    service: ""
    
snowflake:
  accountName: "FKGRCCP-ES23892"
  warehouse: "COMPUTE_WH"
  database: "MSTECH"
  schema: "BFS"
  user: "msrao2829"
  password: "Deloitte@266227"
  role: "ACCOUNTADMIN"