#%RAML 1.0 Library
usage:
traits:
  transactionId: !include /libraries/common/traits/headersTransactionIdTraits.raml
  departureLocationCode: !include /libraries/common/traits/queryParamsDepartureLocationCodeTraits.raml
  destinationLocationCode: !include /libraries/common/traits/queryParamsDestinationLocationCodeTraits.raml